CREATTABLE customers_copy
CREATTABLE customers_copy
CREATTABLE customers_copy
CREATTABLE customers_copy
CREATTABLE customers_copy
CREATTABLE customers_copy
LIKE mysql_test1.customers;
LIKE mysql_test1.customers;
LIKE mysql_test1.customers;
LIKE mysql_test1.customers;
LIKE mysql_test1.customers;
LIKE mysql_test1.customers;
LIKE mysql_test1.customers;
LIKE mysql_test1.customers;
LIKE mysql_test1.customers;
LIKE mysql_test1.customers;
