DELIMITER $$
CREATE EVENT IF NOT EXISTS event_insert
ON SCHEDULE EVERY 1 MONTH 
STARTS CURDATE()+INTERVAL 1 MONTH
ENDS'2016-12-31'
DO 
BEGIN 
IF YEAR(CURDATE())<2016 THEN
  INSERT INTO customers
  VALUES(NULL,'daijun','M','beijing','haiding');
END IF;
END $$
